server:
  port: ${PORT:8080}

spring:
  application:
    name: verdantiq-backend
  data:
    mongodb:
      database: ecosphere
      uri: ${MONGODB_URI:mongodb://localhost:27017/ecosphere}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION_MS:86400000}
